travis:
  secure:
    BINSTAR_TOKEN: Ru5Qh/ECEd6rT3xfo0ThMw+9eIDiu2UN5XtgmeCPBSDaSa0cu2p8SKs9F8mlgohjIHJVEScqCODqH07lhrkbO+3pctB1978hEg729eJNOTkWG16vam6Y58ahiSo6qkfFlu+o7b6NL57LxfkZrosT4fQ6H+yUqlG94UHwuvmZuSWaForsiYlZ5VICSIQ+CHiuU9QDwiXXOOyc6HyLxm/Hq9RR7Y7O6o8vcL/KhaZVQl9iw+CClpR9vDQUSp/0oTxF6hV2u80+XSHuFiRIouJr3pwm8/IxqJ5PaV/UqDEPu2LY+tU0ledm9o+IKSqI7xCQn+MVKW66Iw59qn9bPcn75SE+yB7Iz0ir5ORBY3Ph+xoD4eNwRE4x/hBJPsJSIAHy2+6sud5QcfxFq3U+TVSLmraJYY3O8WjuvNSjP2k18eZkjEKOsjtz0GE8S7yc0POh0JSSmj7dHN8BpaFhs+4ljftT/GX/1PLWSqauMTVCCK5EqIFTJ5zE/CrE3LOTu2YipZDQYmjeMD3BqwyhjAO9qo1NKM2pCoGMol5/biR/vSfGX9S89kPR9m+YJUKpAJSm44kGaDTijHSWy9/+9GFETUj0OJZOp0F4hqmBp3yVuMCk/S3gbyvuvsWcbZ1Mou1IaUARtQhENeVvusgDoxoYdXJSQwEWJEV4U6jDEO/P22M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
